file.open("test.txt", "w")
file.write('fistr\rfirstn\nsecondrn\rnthirdr\rthirdn\nlastrn\rn')
file.close()
file.open("test.txt", "r")
print(file.readline())
print(file.read())
if (file.readline() == nil) then
print("Nil\n")
end
file.close()
print("---------------------------------------------------------------")
file.open("test.txt", "a+")
file.writeline('aaaa')
print(file.read())
file.flush()
print(file.read())
print("Cursor Set\n")
file.seek("set")
print(file.read())
file.close()
print("---------------------------------------------------------------")
file.open("test.txt", "a+")
file.writeline('aaaa')
file.flush()
print(file.read())
print("Cursor Set\n")
file.seek("set")
print(file.read())
file.close()
print("---------------------------------------------------------------")
file.open("test.txt", "w")
file.write('')
file.close()
print("---------------------------------------------------------------")
l = file.list()
for k,v in pairs(l) do
      print("name:"..k..", size:"..v)
end