# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40f62a76e4612517ff4b3e12a54a53e613f9cc5a777976c4a718d89cb9ff9104e283780b16d62f0aaf9cf09a08b6e1cb87fc8daa5beac18308533f9bf3dc357

test:
  secret_key_base: 90016ddf0ec57b9e50a02603c3d224d6b9ce7431c1b8a8406fb3ed1f9ff580994bc2d2ae2c866c91dd73af8863f89663b08faff89d6ec4cb9c6f9487c2902168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
